---
apiVersion: v1
kind: ConfigMap
metadata:
  name: wordpress-cm
  labels:
    app: wordpress
data:
  WORDPRESS_DB_HOST: wordpress-db-cluster-mysql.wordpress.svc.cluster.local
  WORDPRESS_DB_USER: root 

---
apiVersion: app/v1

